theverge:
  name: The Verge
  url: https://www.theverge.com/rss/index.xml
  category: Tech

techcrunch:
  name: TechCrunch
  url: https://techcrunch.com/feed/
  category: Tech

openslime:
  name: OpenSlime
  url: https://openslime.it/feed/
  category: Tech

osnews:
  name: OSnews
  url: https://www.osnews.com/feed/
  category: Tech

404media:
  name: 404 Media
  url: https://www.404media.co/rss/
  category: News

dailydot:
  name: The Daily Dot
  url: https://www.dailydot.com/feed/
  category: News

dexerto:
  name: Dexerto
  url: https://www.dexerto.com/feed/
  category: News

gamingtalker:
  name: GamingTalker
  url: https://www.gamingtalker.it/feed/
  category: Games

nintendo-uk:
  name: Nintendo UK
  url: https://www.nintendo.com/en-gb/news.xml
  category: Games

nintendo-it:
  name: Nintendo Italia
  url: https://www.nintendo.com/it-it/news.xml
  category: Games

nintendo-jp:
  name: Nintendo Japan
  url: https://www.nintendo.co.jp/news/whatsnew.xml
  category: Games

duolingo:
  name: Duolingo Blog
  url: https://blog.duolingo.com/rss/
  category: Blogs

sanrio:
  name: Sanrio Blogs
  url: https://www.sanrio.com/blogs/sanrio.atom
  category: Blogs

sanrio-eu:
  name: Sanrio Europe Blog
  url: https://www.sanrio.eu/feed/
  category: Blogs

octospacc:
  name: fritto misto di octospacc
  url: https://octospacc.altervista.org/author/minioctt/feed/
  category: Blogs

spaccinc:
  name: Spacc Inc.
  url: https://rsshub.app/telegram/channel/SpaccInc
  website: https://t.me/SpaccInc
  category: Fun

creeperiano99:
  name: Creeperiano99
  url: https://rsshub.app/telegram/channel/Creeperiano99Channel
  website: https://t.me/Creeperiano99Channel
  category: Blogs

dailycogito:
  name: Il Substack del Daily Cogito
  url: https://dailycogito.substack.com/feed
  category: Blogs

xkcd:
  url: https://xkcd.com/rss.xml
  category: Fun

theonion:
  name: The Onion
  url: https://theonion.com/feed/
  category: Fun

thepudding:
  name: The Pudding
  url: https://pudding.cool/rss.xml
  category: Fun

notiziolemau:
  name: Notiziole di .mau.
  url: https://xmau.com/wp/notiziole/feed/
  category: Blogs

ritaglimau:
  name: ritagli di .mau.
  url: https://mau.tumblr.com/rss
  category: Blogs
