theverge:
  name: The Verge
  url: https://www.theverge.com/rss/index.xml
  category: Tech

techcrunch:
  name: TechCrunch
  url: https://techcrunch.com/feed/
  category: Tech

openslime:
  name: OpenSlime
  url: https://openslime.it/feed/
  category: Tech

osnews:
  name: OSnews
  url: https://www.osnews.com/feed/
  category: Tech

404media:
  name: 404 Media
  url: https://www.404media.co/rss/
  category: News

dailydot:
  name: The Daily Dot
  url: https://www.dailydot.com/feed/
  category: News

dexerto:
  name: Dexerto
  url: https://www.dexerto.com/feed/
  category: News

ign:
  name: IGN
  url: https://www.ign.com/rss/v2/articles/feed
  category: Tech

gamingtalker:
  name: GamingTalker
  url: https://www.gamingtalker.it/feed/
  category: Games

nintendo-uk:
  name: Nintendo UK
  url: https://www.nintendo.com/en-gb/news.xml
  category: Games

nintendo-it:
  name: Nintendo Italia
  url: https://www.nintendo.com/it-it/news.xml
  category: Games

nintendo-jp:
  name: Nintendo Japan
  url: https://www.nintendo.co.jp/news/whatsnew.xml
  category: Games

duolingo:
  name: Duolingo Blog
  url: https://blog.duolingo.com/rss/
  category: Blogs

sanrio:
  name: Sanrio Blogs
  url: https://www.sanrio.com/blogs/sanrio.atom
  category: Blogs

sanrio-eu:
  name: Sanrio Europe Blog
  url: https://www.sanrio.eu/feed/
  category: Blogs

octospacc:
  name: fritto misto di octospacc
  url: https://octospacc.altervista.org/author/minioctt/feed/
  category: Blogs

spaccinc:
  name: Spacc Inc.
  url: https://rsshub.app/telegram/channel/SpaccInc
  website: https://t.me/SpaccInc
  category: Fun

creeperiano99:
  name: Creeperiano99
  url: https://rsshub.app/telegram/channel/Creeperiano99Channel
  website: https://t.me/Creeperiano99Channel
  category: Blogs

dailycogito:
  name: Il Substack del Daily Cogito
  url: https://dailycogito.substack.com/feed
  category: Blogs

xkcd:
  url: https://xkcd.com/rss.xml
  category: Fun

theonion:
  name: The Onion
  url: https://theonion.com/feed/
  category: Fun

lercio:
  name: Lercio
  url: https://www.lercio.it/feed/
  category: Fun

reductress:
  name: Reductress
  url: https://reductress.com/feed/
  category: Fun

thepudding:
  name: The Pudding
  url: https://pudding.cool/rss.xml
  category: Fun

notiziolemau:
  name: Notiziole di .mau.
  url: https://xmau.com/wp/notiziole/feed/
  category: Blogs

ritaglimau:
  name: ritagli di .mau.
  url: https://mau.tumblr.com/rss
  category: Blogs

alfemminile:
  name: fem
  url: https://www.alfemminile.com/rss/
  category: Blogs

hdblog:
  name: HDBlog.it
  url: https://www.hdblog.it/feed/
  category: Tech

dday:
  name: DDay.it
  url: https://www.dday.it/feed
  category: Tech

arstechnica:
  name: Ars Technica
  url: https://arstechnica.com/feed/
  category: Tech

simsaladream:
  url: https://simsaladream.wordpress.com/feed/
  category: Blogs

feddit-devol:
  name: Feddit - Devol
  url: https://feddit.it/feeds/c/devol.xml?sort=New
  category: Feeds

feddit-openstreetmap_it:
  name: Feddit - OpenStreetMap Italia
  url: https://feddit.it/feeds/c/openstreetmap_it.xml?sort=New
  category: Feeds

feddit-caffeitalia:
  name: Feddit - Caffé Italia
  url: https://feddit.it/feeds/c/caffeitalia.xml?sort=New
  category: Feeds

feddit-memita:
  name: Feddit - Meme Italiani
  url: https://feddit.it/feeds/c/memita.xml?sort=New
  category: Fun

feddit-matematica:
  name: Feddit - Matematica
  url: https://feddit.it/feeds/c/matematica.xml?sort=New
  category: Feeds

feddit-giappone:
  name: Feddit - Giappone
  url: https://feddit.it/feeds/c/giappone.xml?sort=New
  category: Feeds

animalcrossinglife:
  name: Animal Crossing Life
  url: https://animalcrossinglife.com/feed
  category: Games

animalcrossingworld:
  name: Animal Crossing World
  url: https://animalcrossingworld.com/feed/
  category: Games

kikifrommeadow:
  name: Kiki From Meadow
  url: https://kikifrommeadow.com/feed/
  category: Blogs

jvgs:
  name: Jeff's Gaming Blog
  url: https://www.jvgs.net/blog/feed/
  category: Games

zechs:
  name: Zechs.it
  url: https://www.zechs.it/feed/
  category: Series

gundamverse:
  name: Gundamverse.it
  url: https://gundamverse.blogspot.com/feeds/posts/default
  category: Series

meikasensei:
  name: やさしい日本語ブログ Meika Sensei's Easy Japanese Blog
  url: https://meikasensei.com/feed/
  category: Blogs

nihongoblog:
  name: NIHONGOBLOG
  url: https://www.nihongoschool.co.uk/blog-feed.xml
  category: Blogs
